[package]
name = "nft"
version = "0.1.0"
edition = "2021"

[lib]
name = "proflycontract"
path = "src/proflycontract.rs"
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "21.7.7", features = ["testutils"] }